mybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Effort Controllers ---------------------------------------
  leftWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: mybot_left_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
  rightWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: mybot_right_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}
  camera_position_controller:
    type: position_controllers/JointPositionController
    joint: camera_joint
  gazebo_ros_control/pid_gains:
    camera_joint: {p: 10.0, i: 0.0, d: 0.01}
